name = "WTC To The Sky"
author = "Falphir & ArneSW"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "da95e0a0efc71f522996786bf36d913ffeb4998f4ba0d550189c89cf9b41bab8"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.234"
