name = "WTC To The Sky"
author = "Falphir & ArneSW"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2b62dd745d81e9953db98f8f4936ae9c7018959c855e09c037961ed330aaeeab"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.234"
