name = "WTC To The Sky"
author = "Falphir & ArneSW"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "15cd834f53d1e81c297a8bdbacc4af9337e914ce64b8b09ddbb55cc966d1d332"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.252"

[options]
acceptable-game-versions = ["1.21.1"]
